version: '3.8'

services:
  postgres:
    container_name: nest-clean-postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-clean
  
  cache: 
    container_name: nest-clean-cache
    image: redis
    ports:
      - 6379:6379
    